package com.example.facebuilderapi.util

/**
 * FaceBuilder consistent topology vertex indices for facial landmarks. These indices are the same
 * across ALL models generated by the FaceBuilder API.
 */
object HeadLandmarks {
    const val NOSE_BRIDGE = 5625
    const val LEFT_EYE_INNER = 9911
    const val RIGHT_EYE_INNER = 4341
    const val LEFT_EAR_TRAGUS = 10868
    const val RIGHT_EAR_TRAGUS = 12778
}

/** Extracted 3D positions (x, y, z) of facial landmarks from a head model. */
data class FaceLandmarks(
        val noseBridge: FloatArray,
        val leftEyeInner: FloatArray,
        val rightEyeInner: FloatArray,
        val leftEarTragus: FloatArray,
        val rightEarTragus: FloatArray
)

/**
 * Anchor points extracted from a glasses model's glTF extras metadata. Positions are in the glasses
 * model's local coordinate space.
 */
data class GlassesAnchors(
        val noseBridge: FloatArray,
        val leftLensCenter: FloatArray,
        val rightLensCenter: FloatArray,
        val leftEarTip: FloatArray,
        val rightEarTip: FloatArray
)
